SELECT 
  TABLE_NAME,
  TABLE_ROWS,
  ROUND(DATA_LENGTH / 1024 / 1024, 2) as data_mb,
  ROUND(INDEX_LENGTH / 1024 / 1024, 2) as index_mb,
  ROUND((DATA_LENGTH + INDEX_LENGTH) / 1024 / 1024, 2) as total_mb
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'mrl'
ORDER BY (DATA_LENGTH + INDEX_LENGTH) DESC
LIMIT 20;
