SELECT 
  TABLE_NAME,
  COLUMN_NAME,
  DATA_TYPE,
  COLUMN_TYPE,
  CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'mrl'
  AND (DATA_TYPE IN ('blob', 'mediumblob', 'longblob', 'text', 'mediumtext', 'longtext')
       OR CHARACTER_MAXIMUM_LENGTH > 10000)
ORDER BY TABLE_NAME, COLUMN_NAME;
