CREATE TABLE IF NOT EXISTS orders (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  avatar_id VARCHAR(36) NULL,
  title VARCHAR(200) NOT NULL,
  description LONGTEXT NULL,
  content_type VARCHAR(50) DEFAULT 'text',
  platforms LONGTEXT NULL,
  primary_platform VARCHAR(50) NULL,
  requirements LONGTEXT NULL,
  budget DECIMAL(10,2) DEFAULT 0,
  price DECIMAL(10,2) DEFAULT 0,
  status VARCHAR(50) DEFAULT 'pending_payment',
  result LONGTEXT NULL,
  expected_quantity INT DEFAULT 1,
  quantity_per_avatar INT DEFAULT 1,
  avatar_count INT DEFAULT 0,
  is_paid TINYINT DEFAULT 0,
  deadline DATETIME NULL,
  content_deadline_at DATETIME NULL,
  priority INT DEFAULT 0,
  order_type VARCHAR(50) NULL,
  assigned_to VARCHAR(36) NULL,
  latitude DECIMAL(10,6) NULL,
  longitude DECIMAL(10,6) NULL,
  location_text VARCHAR(500) NULL,
  target_audience VARCHAR(200) NULL,
  publish_proof_url LONGTEXT NULL,
  publish_verified TINYINT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  completed_at DATETIME NULL,
  INDEX idx_user_id (user_id),
  INDEX idx_status (status),
  INDEX idx_created_at (created_at),
  INDEX idx_orders_open_core (is_paid, status, priority, created_at),
  INDEX idx_orders_open_platform (primary_platform, is_paid, status, priority, created_at),
  INDEX idx_user_status_created_at (user_id, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_dispatch_requests (
  id VARCHAR(36) PRIMARY KEY,
  order_id VARCHAR(36) NOT NULL,
  avatar_id VARCHAR(36) NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  target_avatar_id VARCHAR(36) NULL,
  platform VARCHAR(50) NULL,
  status VARCHAR(50) DEFAULT 'pending',
  expires_at DATETIME NULL,
  responded_at DATETIME NULL,
  accepted_at DATETIME NULL,
  reject_reason VARCHAR(500) NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_order_id (order_id),
  INDEX idx_avatar_id (avatar_id),
  INDEX idx_status (status),
  INDEX idx_expires_at (expires_at),
  INDEX idx_odr_order_status_created (order_id, status, created_at),
  UNIQUE KEY uniq_order_avatar (order_id, avatar_id),
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS content_generation_requests (
  id VARCHAR(36) PRIMARY KEY,
  order_id VARCHAR(36) NOT NULL,
  avatar_id VARCHAR(36) NOT NULL,
  user_id VARCHAR(36) NULL,
  platform VARCHAR(50) NULL,
  platforms LONGTEXT NULL,
  status VARCHAR(50) DEFAULT 'queuing',
  content_type VARCHAR(50) NULL,
  content_quantity INT DEFAULT 1,
  content LONGTEXT NULL,
  images LONGTEXT NULL,
  video_url LONGTEXT NULL,
  publish_status LONGTEXT NULL,
  publish_feedback LONGTEXT NULL,
  publish_url LONGTEXT NULL,
  publish_screenshot LONGTEXT NULL,
  verification_status VARCHAR(20) DEFAULT 'pending',
  verified_at TIMESTAMP NULL,
  config LONGTEXT NULL,
  seedance_task_id VARCHAR(128) NULL,
  error TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_order_id (order_id),
  INDEX idx_avatar_id (avatar_id),
  INDEX idx_status (status),
  INDEX idx_cgr_status_updated_at (status, updated_at),
  INDEX idx_seedance_task_id (seedance_task_id),
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_results (
  id VARCHAR(36) PRIMARY KEY,
  order_id VARCHAR(36) NOT NULL,
  avatar_id VARCHAR(36) NULL,
  user_id VARCHAR(36) NULL,
  result LONGTEXT NULL,
  customer_rating INT NULL,
  customer_comment LONGTEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_order_id (order_id),
  INDEX idx_avatar_id (avatar_id),
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS earnings (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  type VARCHAR(50) NULL,
  amount DECIMAL(10,2) DEFAULT 0,
  status VARCHAR(50) DEFAULT 'pending',
  source VARCHAR(200) NULL,
  description VARCHAR(500) NULL,
  avatar_id VARCHAR(36) NULL,
  order_id VARCHAR(36) NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_user_id (user_id),
  INDEX idx_type (type),
  INDEX idx_status (status),
  UNIQUE KEY uniq_earn_order_avatar_type (order_id, avatar_id, type),
  FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS withdrawals (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  amount DECIMAL(10,2) DEFAULT 0,
  method VARCHAR(50) NULL,
  account VARCHAR(200) NULL,
  status VARCHAR(50) DEFAULT 'pending',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_user_id (user_id),
  INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS transactions (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  type VARCHAR(50) NULL,
  amount DECIMAL(10,2) NULL,
  balance_before DECIMAL(10,2) DEFAULT 0,
  balance_after DECIMAL(10,2) DEFAULT 0,
  description VARCHAR(500) NULL,
  source_id VARCHAR(36) NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_user_id (user_id),
  INDEX idx_type (type),
  INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS avatar_notifications (
  id VARCHAR(36) PRIMARY KEY,
  avatar_id VARCHAR(36) NOT NULL,
  order_id VARCHAR(36) NULL,
  notification_type VARCHAR(50) NULL,
  title VARCHAR(200) NULL,
  content LONGTEXT NULL,
  is_read TINYINT DEFAULT 0,
  data LONGTEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_avatar_id (avatar_id),
  INDEX idx_is_read (is_read)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS referrals (
  id VARCHAR(36) PRIMARY KEY,
  referrer_id VARCHAR(36) NOT NULL,
  referred_id VARCHAR(36) NOT NULL,
  reward_amount DECIMAL(10,2) DEFAULT 0,
  status VARCHAR(20) DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_referrals_referrer_created (referrer_id, created_at),
  INDEX idx_referrals_referred_status (referred_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_tasks (
  task_id VARCHAR(64) NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  avatar_id VARCHAR(36) NULL,
  task_description LONGTEXT NULL,
  conversation_id VARCHAR(64) NULL,
  conversation_history LONGTEXT NULL,
  attachments LONGTEXT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  result LONGTEXT NULL,
  error LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  completed_at DATETIME NULL,
  expires_at DATETIME NULL,
  PRIMARY KEY (task_id),
  INDEX idx_agent_tasks_user (user_id),
  INDEX idx_agent_tasks_status (status),
  INDEX idx_agent_tasks_expires (expires_at),
  INDEX idx_agent_tasks_user_status (user_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_task_progress (
  id BIGINT NOT NULL AUTO_INCREMENT,
  task_id VARCHAR(64) NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  type VARCHAR(50) NOT NULL,
  message LONGTEXT NOT NULL,
  data LONGTEXT NULL,
  timestamp_ms BIGINT NOT NULL,
  status VARCHAR(20) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_agent_task_progress_task (task_id),
  INDEX idx_agent_task_progress_user_task (user_id, task_id),
  INDEX idx_agent_task_progress_ts (timestamp_ms)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
