export default defineAppConfig({
  pages: [
    // 主包：TabBar页面（第一个为默认页）+ 必须在主包的页面
    'pages/index/index',
    'pages/mind-chat/index',
    'pages/avatar-square/index',
    'pages/work-square/index',
    'pages/profile/index',
    'pages/login/index',
    'pages/user-agreement/index',
    'pages/privacy-policy/index',
    'pages/webview/index',
    'pages/publish-redirect/index',
  ],
  subPackages: [
    {
      root: 'package-order',
      name: 'order',
      pages: [
        'pages/order-list/index',
        'pages/order-square/index',
        'pages/order-create/index',
        'pages/order-create-new/index',
        'pages/order-step-management/index',
        'pages/order-step-preview/index',
        'pages/order-detail/index',
        'pages/order-processing/index',
        'pages/order-accept-task/index',
        'pages/order-acceptance/index',
        'pages/order-matching/index',
        'pages/order-content-creation/index',
        'pages/order-asset-waiting/index',
        'pages/order-publish-guide/index',
        'pages/order-feedback/index',
        'pages/order-publish-feedback/index',
        'pages/order-acceptance-feedback/index',
        'pages/order-completed/index',
        'pages/pending-order/index',
        'pages/order-stats/index',
      ],
    },
    {
      root: 'package-profile',
      name: 'profile',
      pages: [
        'pages/settings/index',
        'pages/security/index',
        'pages/notifications/index',
        'pages/followers/index',
        'pages/about/index',
        'pages/help/index',
        'pages/feedback/index',
        'pages/earning-center/index',
        'pages/referral-center/index',
        'pages/referral-list/index',
        'pages/earnings-wall/index',
        'pages/my-favorites/index',
      ],
    },
    {
      root: 'package-avatar',
      name: 'avatar',
      pages: [
        'pages/avatar-profile/index',
        'pages/avatar-recommend/index',
        'pages/avatar-order-completed/index',
        'pages/avatar-manage/index',
        'pages/avatar-create/index',
        'pages/avatar-settings/index',
        'pages/avatar-account-add/index',
        'pages/avatar-account-config/index',
        'pages/oauth-webview/index',
        'pages/avatar-friends/index',
        'pages/avatar-orders/index',
        'pages/palm-reading/index',
        'pages/voice-call/index',
        'pages/subscription/index',
        'pages/friendship-management/index',
        'pages/generated-content/index',
        'pages/social/index',
        'pages/messages/index',
      ],
    },
    {
      root: 'package-skill',
      name: 'skill',
      pages: [
        'pages/skill-create/index',
        'pages/skill-training/index',
        'pages/skills-square/index',
        'pages/skill-try/index',
        'pages/palm-reading/index',
        'pages/fashion-makeover/index',
        'pages/wechat-mp-article/index',
      ],
    },
    {
      root: 'package-group-bot',
      name: 'groupbot', // eslint-disable-line no-restricted-syntax
      pages: [
        'pages/group-list/index',
        'pages/group-chat/index',
      ],
    },
    {
      root: 'package-admin',
      name: 'admin',
      pages: [
        'pages/login/index',
        'pages/dashboard/index',
        'pages/users/index',
        'pages/users/detail/index',
        'pages/avatars/index',
        'pages/orders/index',
        'pages/finance/index',
        'pages/content/index',
        'pages/referral/index',
        'pages/settings/index',
        'pages/skills/index',
      ],
    },
    {
      root: 'package-coin',
      name: 'coin',
      pages: [
        'pages/index/index',
        'pages/recharge/index',
        'pages/transactions/index',
      ],
    },
    {
      root: 'package-avatar-square',
      name: 'avatar-square',
      pages: [
        'pages/avatar-public-detail/index',
        'pages/avatar-owner-detail/index',
        'pages/avatar-settings/index',
        'pages/avatar-work-manage/index',
        'pages/avatar-work-detail/index',
        'pages/work-square-detail/index',
        'pages/work-content-detail/index',
      ],
    },
    {
      root: 'package-my-avatar',
      name: 'my-avatar',
      pages: [
        'pages/my-avatar/index',
        'pages/avatar-onboarding/index',
        'pages/avatar-create-step1/index',
        'pages/avatar-create-step2/index',
        'pages/skill-certify/index',
        'pages/skill-certify-result/index',
        'pages/template-list/index',
        'pages/template-detail/index',
        'pages/template-use/index',
        'pages/template-use-result/index',
        'pages/custom-template-create/index',
      ],
    },
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: '分身大师',
    navigationBarTextStyle: 'black',
  },
  permission: {
    'scope.userFuzzyLocation': {
      desc: '你的位置信息将用于定位分身当前位置，展示附近的动态和内容',
    },
  },
  requiredPrivateInfos: ['getFuzzyLocation'],
  tabBar: {
    color: '#9CA3AF',
    selectedColor: '#7B3FE4',
    backgroundColor: '#ffffff',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: './tabbar-icons/home.png',
        selectedIconPath: './tabbar-icons/home-active.png',
      },
      // {
      //   pagePath: 'pages/mind-chat/index',
      //   text: '分身',
      //   iconPath: './tabbar-icons/message-circle.png',
      //   selectedIconPath: './tabbar-icons/message-circle-active.png',
      // },
      {
        pagePath: 'pages/avatar-square/index',
        text: '分身广场',
        iconPath: './tabbar-icons/users.png',
        selectedIconPath: './tabbar-icons/users-active.png',
      },
      {
        pagePath: 'pages/work-square/index',
        text: '动态广场',
        iconPath: './tabbar-icons/sparkles.png',
        selectedIconPath: './tabbar-icons/sparkles-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: './tabbar-icons/user.png',
        selectedIconPath: './tabbar-icons/user-active.png',
      },
    ],
  },
})
