export default defineAppConfig({
  pages: [
    // 主包：TabBar页面（第一个为默认页）
    'pages/index/index',
    'pages/mind-chat/index',
    'pages/profile/index',
    'pages/login/index',
    'pages/webview/index',
    'pages/publish-redirect/index',
    // 广场页面（不在TabBar）
    'pages/social/index',
    // 订单相关
    'pages/order/order-list/index',
    'pages/order/order-create/index',
    'pages/order/order-detail/index',
    'pages/order/order-processing/index',
    'pages/order/order-acceptance/index',
    'pages/order/order-matching/index',
    'pages/order/order-content-creation/index',
    'pages/order/order-publish-guide/index',
    'pages/order-feedback/index',
    'pages/order-publish-feedback/index',
    'pages/order-acceptance-feedback/index',
    'pages/order-completed/index',
    'pages/pending-order/index',
    'pages/order-stats/index',
    // 个人中心
    'pages/profile/settings/index',
    'pages/profile/security/index',
    'pages/profile/notifications/index',
    'pages/profile/followers/index',
    'pages/feedback/index',
    'pages/profile/about/index',
    'pages/profile/help/index',
    // 收益
    'pages/earning-center/index',
    'pages/referral-center/index',
    'pages/earnings-wall/index',
    // 分身相关
    'pages/avatar-profile/index',
    'pages/avatar-recommend/index',
    'pages/avatar-order-completed/index',
    'pages/avatar/avatar-manage/index',
    'pages/avatar/avatar-create/index',
    'pages/avatar/avatar-settings/index',
    'pages/avatar/avatar-account-add/index',
    'pages/avatar/avatar-account-config/index',
    'pages/avatar/avatar-friends/index',
    'pages/avatar-orders/index',
    // 功能页面
    'pages/messages/index',
    'pages/palm-reading/index',
    'pages/voice-call/index',
    'pages/subscription/index',
    'pages/skill-create/index',
    'pages/skill-training/index',
    'pages/skills-square/index',
    'pages/friendship-management/index',
    'pages/generated-content/index',
    // 管理后台
    'pages/admin/login/index',
    'pages/admin/dashboard/index',
    'pages/admin/users/index',
    'pages/admin/users/detail/index',
    'pages/admin/avatars/index',
    'pages/admin/orders/index',
    'pages/admin/finance/index',
    'pages/admin/content/index',
    'pages/admin/referral/index',
    'pages/admin/settings/index',
    'pages/admin/skills/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: '分身大师',
    navigationBarTextStyle: 'black',
  },
  permission: {
    'scope.userLocation': {
      desc: '你的位置信息将用于定位分身当前位置，展示附近的动态和内容',
    },
  },
  tabBar: {
    color: '#9CA3AF',
    selectedColor: '#7B3FE4',
    backgroundColor: '#ffffff',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: './assets/tabbar/home.png',
        selectedIconPath: './assets/tabbar/home-active.png',
      },
      {
        pagePath: 'pages/mind-chat/index',
        text: '分身',
        iconPath: './assets/tabbar/message-circle.png',
        selectedIconPath: './assets/tabbar/message-circle-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: './assets/tabbar/user.png',
        selectedIconPath: './assets/tabbar/user-active.png',
      },
    ],
  },
})
