export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/mind-chat/index',
    'pages/avatar-profile/index',
    'pages/profile/index',
    'pages/social/index',
    'pages/skills-square/index',
    'pages/palm-reading/index',
    'pages/settings/index',
    'pages/avatar-order-completed/index',
    'pages/avatar-recommend/index',
    'pages/order-stats/index',
    'pages/security/index',
    'pages/earning-center/index',
    'pages/referral-center/index',
    'pages/skill-create/index',
    'pages/skill-training/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: '智能分身',
    navigationBarTextStyle: 'black',
  },
  tabBar: {
    color: '#999999',
    selectedColor: '#6366f1',
    backgroundColor: '#ffffff',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/avatar-profile/index',
        text: '分身',
        iconPath: './assets/tabbar/users.png',
        selectedIconPath: './assets/tabbar/users-active.png',
      },
      {
        pagePath: 'pages/mind-chat/index',
        text: '对话',
        iconPath: './assets/tabbar/message-circle.png',
        selectedIconPath: './assets/tabbar/message-circle-active.png',
      },
      {
        pagePath: 'pages/social/index',
        text: '广场',
        iconPath: './assets/tabbar/house.png',
        selectedIconPath: './assets/tabbar/users-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: './assets/tabbar/user.png',
        selectedIconPath: './assets/tabbar/user-active.png',
      },
    ],
  },
  subPackages: [
    {
      root: 'avatar',
      pages: [
        'avatar-create/index',
        'avatar-manage/index',
        'avatar-friends/index',
        'avatar-settings/index',
        'avatar-account-config/index',
        'avatar-account-add/index',
      ],
    },
    {
      root: 'order',
      pages: [
        'order-create/index',
        'order-list/index',
        'order-detail/index',
        'order-matching/index',
        'order-acceptance/index',
        'order-content-creation/index',
        'order-feedback/index',
        'order-processing/index',
        'order-publish-feedback/index',
        'pending-order/index',
        'avatar-orders/index',
      ],
    },
  ],
})
